
List<String> listephrasalverbs =[
  'Aim At: To point a weapon at someone or something.',
  'Ask For: To request something.',
  'Ask Out: When you ask someone to go with you to a certain place or for a special occasion, to spend time together and have fun. If one or both parties involved are interested in a romantic way, then it is considered a date.',
  'Back Down: To withdraw your position in a fight, argument, plan, etc.',
  'Back Off: When you leave an emotional situation, or to allow someone to handle something alone.',
  'Back Up: To walk or drive a vehicle backwards.',
  'Beat Up: When someone punches, kicks, or hits someone repeatedly using fists or with an object.',
  'Beef Up: To make changes or an improvement.',
  'Believe In: To feel confident about something or someone.',
  'Bite Off: To use your teeth to bite a piece of something.',
  'Blow Away: When the wind moves an object or person from where it was.',
  'Blow Off: When the wind removes something from its place.',
  'Blow Out: To extinguish or make a flame stop burning.',
  'Blow Up: To make something explode.',
  'Boil Down To: To have determined or analyzed the solution or reason for something.',
  'Break Down: When someone loses self-control and is emotionally and/or mentally agitated. This meaning has a noun form for a situation where someone loses self-control.',
  'Break In: To enter a place illegally and with the use of force.',
  'Break Off: To remove a part of something with force.',
  'Break Out: To escape from a place, situation or way of life.',
  'Break Through: To make a way through a barrier or a surface.',
  'Break Up: To stop a fight.',
  'Bring Back: To return something you’ve borrowed.',
  'Bring Over: To bring someone or something from one place or area to another.',
  'Bring Up: To bring something from a lower level/place to a higher level/place.',
  'Brush Off: To remove something(dust particle, insect, etc) with your hand.',
  'Brush Up: To practice and review your knowledge or a skill that you haven’t used in a while.',
  'Build In/Into: To add a fixture or component to a certain area or place through construction.',
  'Bump Into: When you meet people by accident or unexpectedly.',
  'Burn Down: When someone uses fire to destroy a structure.',
  'Burn Out: When a candle stops burning because there is nothing left to burn.',
  'Burn Up: To destroy something with heat or fire.',
  'Burst Out: To suddenly do or say something.',
  'Butt In: To interrupt a conversation or activity.',
  'Call Back: To call someone again.',
  'Call In: To request that someone come and help.',
  'Call Off: To cancel an event that has been previously planned.',
  'Call Up: To be chosen to take part in a military mission.',
  'Calm Down: To become less violent, nervous, excited or angry.',
  'Care For: To nurture or take care of someone or something.',
  'Carry Away: To do something out of the ordinary due to strong emotions.',
  'Carry On: To continue doing something or to continue on in life despite an obstacle.',
  'Carry Out: To move something or someone from one place to another using your arms or an object.',
  'Catch On: To understand or realize something.',
  'Catch Up: To move faster to reach someone or something that is ahead of you.',
  'Cheat On: When you are emotionally and/or sexually unfaithful to your girlfriend/boyfriend or spouse.',
  'Check In: To register at a hotel or airport upon arrival.',
  'Check Out: To leave a hotel or other form of an accommodation after your stay there.',
  'Chicken Out: To refrain from doing something because of fear.',
  'Chop Up: To cut something into pieces with a knife.',
  'Clean Out: To clean or clear the inside of something thoroughly.',
  'Clear Out: To remove things completely from an area or place.',
  'Clear Up: To do something to solve a problem or a misunderstanding.',
  'Clog Up: When something in a drain or valve prevents the flow of water or other liquids',
  'Close Down: When the activities or services of a business permanently end.',
  'Close Off: To block an entrance or pathway.',
  'Come About: When something happens or occurs.',
  'Come Across: The way other people perceive something or someone.',
  'Come Apart: When something breaks or separates piece by piece.',
  'Come Back: To return to a place.',
  'Come Down: To move from a higher to a lower position or from north to south.',
  'Come Down To: When a situation is reduced to a certain outcome.',
  'Come Down With: When you start to experience the symptoms of a disease or illness.',
  'Come In: When someone or something enters a place, building, or room.',
  'Come Off: When something is removed or breaks off from where it was originally attached to.',
  'Come On: To appear on television or be heard on the radio.',
  'Come Out: To leave a place.',
  'Come Over: To make a visit.',
  'Come Through: When someone or something expected arrives.',
  'Come Up: When something appears or happens, either expected or unexpected.',
  'Come Up With: When you think of a solution, idea, plan, or excuse.',
  'Con Into: To persuade someone to do something through lies and deception.',
  'Con Out Of: To persuade someone to give or do something through lies and deception.',
  'Cool Off: To lose temperature.',
  'Count On: To rely on someone for support when you need it most.',
  'Count Up: To count all of something or people in a group.',
  'Cover Up: To use something to conceal something else.',
  'Crack Down: To take more action than usual against wrongdoing.',
  'Cross Off: To remove or delete someone or something from a list.',
  'Cut Back: When you spend less money on something.',
  'Cut Down: To do less of something or to use something in smaller amounts.',
  'Cut Off: To completely remove or separate a part of something by cutting it with something sharp like a knife or a pair of scissors, etc.',
  'Cut Out: To remove something using a knife or a pair of scissors.',
  'Cut Up: When you use a knife or scissors to cut something into several pieces.',
  'Deal With : When you do everything you must do to solve a problem or complete.',
  'Do Away With : To dispose of something.',
  'Do Over : To do something again in order to improve or correct mistakes.',
  'Do With : To make a connection between two or more things.',
  'Do Without : To manage well without something or someone.',
  'Doze Off : To go to sleep unintentionally.',
  'Dress Up : To wear formal clothes, or a costume for a special occasion.',
  'Drop In : To visit someone unexpectedly or without making arrangements first.',
  'Drop Off : To gradually decline/become less.',
  'Drop Out : To quit a school program or training course.',
  'Dry Off : To dry something or a surface quickly.',
  'Dry Out : To remove water or other liquid from a container.',
  'Dry Up : When all the liquid and/or moisture evaporates.',
  'Eat Up : When someone consumes all their food.',
  'Empty Out : To remove everyone or everything from a space.',
  'End Up : The end result of something planned or unplanned.',
  'Fall Apart : When something breaks all at once or piece by piece.',
  'Fall Behind : To move slower than others.',
  'Fall Down : To fall to the ground.',
  'Fall For : When you have an intense attraction to something or someone.',
  'Fall Off : When something drops to a lower level.',
  'Fall Out : To fall from or through something.',
  'Fall Over : When someone or something falls from an upright position to the ground.',
  'Fall Through : If things do not go as planned, or if a plan, deal or agreement fails.',
  'Feel Up To : When you have/don’t have the energy and confidence to do something.',
  'Fight Back : When you defend yourself/resist an attack, or make an effort against an opponent in a competition.',
  'Figure On : To expect or plan for something.',
  'Fill In : To add personal information in the blank spaces of an official document.',
  'Fill Out : To complete a form.',
  'Fill Up : To fill something completely.',
  'Find Out : To become aware of something or someone.',
  'Fix Up : To make plans or arrangements with someone or for others.',
  'Flip Out : To become very mad or lose control over your emotions.',
  'Float Around : When an object or a person is near, but you cannot pinpoint the exact location.',
  'Follow Up : To find out more about something, or take further action in regards to it.',
  'Fool Around : To waste time doing unimportant or silly things.',
  'Freak Out : When someone becomes irrationally upset or angry, sometimes to the point of confusion.',
  'Get Ahead : To become successful in the professional environment or make consistent progress in life.',
  'Get Along : To have good interactions with others.',
  'Get Around To : To do something that needed to get done at an earlier time.',
  'Get Away : To escape from something.',
  'Get Back : To return to a place.',
  'Get Back At : To get revenge.',
  'Get Back To : When you talk to someone at a later time either because you are busy or you have obtained additional or new information.',
  'Get Behind : To learn, work, or progress more slowly than others.',
  'Get By : To pass someone or something.',
  'Get Down : To move to a lower place or level.',
  'Get In : To arrive or enter a place, room, building, etc.',
  'Get Off : To leave a form of transportation, except a car.',
  'Get Off On : To be excited or to truly enjoy doing something.',
  'Get On : When you move your body and either stand, sit, lie, kneel, etc. towards something (non-separable).',
  'Get Out : To leave or escape.',
  'Get Out Of : To receive a benefit and/or satisfaction from doing something.',
  'Get Over : To move past an obstacle to the other side.',
  'Get Over With : To finish something that needs to get done.',
  'Get Through : When a message, meaning, or idea is understood or accepted.',
  'Get To : To arrive to or assist someone to a place.',
  'Get Together : To meet and spend time together.',
  'Get Up : To move to a higher level/position.',
  'Give Away : To give something for free or without expecting anything in return.',
  'Give In : To surrender to something.',
  'Give Out : To distribute something.',
  'Give Up : To stop doing something without completing it.',
  'Go About : To take the necessary steps to get something done.',
  'Go After : When you do your best to get something no matter how difficult it is.',
  'Go Ahead : To proceed to do something that you were hesitant about.',
  'Go Along With : To accept or agree with a decision, rule, opinion, etc.',
  'Go Around : To follow a circular path.',
  'Go Away : To move or travel from one place to another place.',
  'Go Back : To return to a place, time, activity, or a person.',
  'Go Back On : When you fail to fulfill a promise you made to someone.',
  'Go Beyond : To be more than or better than what is normal or expected.',
  'Go By : To pass someone or something quickly.',
  'Go Down : To move to a lower position, place, price, level, etc.',
  'Go For : To try to obtain.',
  'Go In : To enter a place, building, room, etc.',
  'Go In For : To enter a place or area for a specific reason.',
  'Go In/Into : To enter a place, room, building, etc. usually through a door.',
  'Go Off : To leave unannounced.',
  'Go On : When something takes place.',
  'Go Out : To leave a place or area you’re in.',
  'Go Over : To review something.',
  'Go Through With : When you make a decision to do something, and actually do it.',
  'Go Up : To move or extend to a higher level or farther North.',
  'Go With : To accompany someone to a place.',
  'Goof Around : To waste time doing silly or unimportant things.',
  'Gross Out : To be disgusted with someone or something.',
  'Grow Out Of : To become too big or too tall for your clothes.',
  'Grow Up : When you physically change from a child to an adult.',
  'Hand Back : When you return something to the person who owns it after the person has given it to you.',
  'Hand In : To give something to a person of authority.',
  'Hand Out : To distribute something free to other people.',
  'Hand Over : To give upon request or demand.',
  'Hang Around : To spend time in a place or an area.',
  'Hang On : When you hold something, often for support of comfort.',
  'Hang Out : To hang something, usually wet clothes, to dry.',
  'Hang Up : To hang clothes or an object on a hook, hanger or rod.',
  'Have On : To wear clothing, cosmetics, perfume, etc.',
  'Head Back : To go to a place where you’ve been before or where you started from.',
  'Head For : When a situation becomes more likely.',
  'Head Toward : To move in the direction where someone or something is.',
  'Hear About : When you learn details about something or someone.',
  'Hear Of : When you learn about something or someone.',
  'Heat Up : To make something warmer or cause a rise in temperature.',
  'Help Out : To assist people with something.',
  'Hit On : To suddenly have a solution to a problem or an interesting idea.',
  'Hold Against : When you don’t forgive or have little respect for someone because of something they did.',
  'Hold Off : To delay something.',
  'Hold On : When you wait for a short time.',
  'Hold Out : To extend your hand or an object in front of you.',
  'Hold Up : To hold someone or something up in the air.',
  'Hook Up : When you connect two electrical devices together.',
  'Hurry Up : To do something quickly.',
  'Keep At : To continue doing an activity even though it may be difficult.',
  'Keep Away : To avoid getting close to someone or something.',
  'Keep Down : To make sound, music and noise minimal.',
  'Keep From : To stop yourself or other people from doing something.',
  'Keep Off : To avoid discussing a particular subject or topic.',
  'Keep On : To continue doing something.',
  'Keep To : When you don’t share information.',
  'Keep Up : To continue to do something.',
  'Kick Back : To illegally pay extra money to someone as part of the price.',
  'Kick Out : To force someone to leave an organization or place.',
  'Knock Off : To use force to cause someone or something to fall from its place, whether intentionally or accidentally.',
  'Knock Out : When someone is struck hard enough to cause them to lose consciousness.',
  'Knock Over : To make contact with something or someone in such a way it or they fall.',
  'Know About : To have knowledge of or be familiar with something.',
  'Lay Down : To place something on a surface or an object.',
  'Lay Off : When a company or business ends a worker’s employment.',
  'Lead Up To : When a period of time or a series of events cause an event, situation or conversation to happen.',
  'Leave Behind : When you don’t take something or someone with you when you leave.',
  'Leave Off : To accidentally or intentionally not include a person or thing on a list.',
  'Leave Out : To not include someone or something.',
  'Leave Over : When you have a portion that still remains from something after you have used or eaten the rest of it.',
  'Let Down : To disappoint someone.',
  'Let In : To allow someone or something to enter a place.',
  'Let Off : To allow someone to leave a car, bus, train etc.',
  'Let On : To tell something that is a secret or private.',
  'Let Out : When you give permission for someone to leave or be released from a place.',
  'Let Up : When someone or something becomes less intense or strong.',
  'Lie Around : To be lazy or to not do anything.',
  'Lift Up : To raise someone or something to a higher level.',
  'Light Up : To illuminate something.',
  'Lighten Up : When a conversation is changed or a person changes to become less serious.',
  'Line Up : To form in a row one after another or side-by-side.',
  'Live With : To share the same residence.',
  'Lock In : To secure people or things behind a closed door.',
  'Lock Out : When you don’t have the key or passcode to enter a secured place.',
  'Lock Up : When you shut the windows and doors of a place or building.',
  'Look Around : To turn your head to see what or who is around you.',
  'Look At : To divert your eyes to someone or something.',
  'Look Down On : When you consider someone or something as unimportant or with little to no value. The opposite of yesterday’s phrasal verb.',
  'Look Forward To : To anticipate a future event because it either makes you happy and/or you benefit from it.',
  'Look Into : To investigate or get more facts about something.',
  'Look Out : To remain alert.',
  'Look Over : To examine or inspect something or someone.',
  'Look Up : When a situation becomes better.',
  'Look Up To : This particular phrasal verb is used to say you view someone with respect and/or admiration.',
  'Luck Out : To have exceptionally good luck.',
  'Make For : To go in a certain direction, typically in a hurry.',
  'Make Of : To understand the meaning of something.',
  'Make Up : To invent a story.',
  'Mess Up : When something is dirty or unorganized.',
  'Mix Up : To put or combine different things together so they’ll merge successfully.',
  'Monkey Around With : To try to play with or repair a device that you have no true knowledge about.',
  'Move In : When you bring your personal belongings and stuff to a new place where you will live. Yesterday’s phrasal verb, Move Out, has the opposite meaning.',
  'Move Out : When you permanently remove all your belongings and personal items from a place where you live or stay.',
  'Narrow Down : To reduce the number of options or possibilities.',
  'Pay Back : When you return money that you owe someone.',
  'Pay For : To purchase merchandise.',
  'Pay Off : To repay money that is owed to a person or entity.',
  'Pay Up : To pay all the money that is owed or asked for.',
  'Pick On : To tease and/or criticize someone over a period of time.',
  'Pick Out : When you are able to recognize something or someone from a group.',
  'Pick Up : To get someone or something from somewhere.',
  'Pile Up : To put things in a pile or heap.',
  'Piss Off : [Informal] To be angry about something.',
  'Plan Ahead : To prepare for a future event or situation.',
  'Plan For : To prepare for a big event or expectation in the future.',
  'Plan On : When you have the intention to do something.',
  'Plug In : To connect an electrical device to an electrical outlet.',
  'Plug In/Into : To connect an electrical appliance/machine to another piece of equipment or to a power source.',
  'Plug Up : To block a narrow passage such as a hole, drain, or pipe so that nothing can flow through.',
  'Point Out : To make someone aware of something.',
  'Point To : When you aim at something or someone using your finger or hand.',
  'Print Out : To produce a hard copy of a computer document.',
  'Pull Off : To succeed in doing something difficult or tricky.',
  'Pull Out : When something or someone leaves a place.',
  'Pull Over : To drive your vehicle to the side of the road to stop.',
  'Pull Through : To recover from an injury or illness.',
  'Punch In : To enter data or record time on a device.',
  'Punch Out : To record the time you leave the workplace using a special clock.',
  'Put Away : To place something where it cannot be seen or isn’t in the way of other things.',
  'Put Back : When something is causing a project to slow down.',
  'Put Down : To place something on a surface or an object.',
  'Put In : When you invest or make a deposit. In this example, the amount almost always separates the verb.',
  'Put Off : To become offended by someone or something.',
  'Put Out : To extend a part of your body.',
  'Put Past : To not be surprised by a person’s actions. [Always used with the negative]',
  'Put To : To cause someone or something to be in a certain state or to do something extra.',
  'Put Together : To assemble or connect the parts of something.',
  'Put Up : To move an object to a higher level.',
  'Put Up To : To encourage or persuade someone to do something.',
  'Put Up With : To tolerate or accept something that you’d rather not.',
  'Ring Up : To call someone on the phone.',
  'Rip Off : When someone asks for a price for something that is too high, when someone cheats or steals.',
  'Rip Up : To tear something (i.e. paper, cloth, etc.) into pieces.',
  'Rule Out : When someone or something is excluded as a possibility.',
  'Run Across : To move or run from one side to the other.',
  'Run Around : To go from one place to another in a hurry.',
  'Run Down : To hit someone or something with a vehicle.',
  'Run Into : When something collides with another object by accident.',
  'Run Out : When people exit a place very quickly. Run In/ Run Into is the opposite of this meaning.',
  'Run Over : When someone is injured or killed by a vehicle.',
  'Run Up : To run from a lower elevation or level to a higher elevation or level.',
  'Screw On : To ensure the top of a container/bottle is sealed.',
  'Screw Out Of : To cheat or deceive someone.',
  'Screw Up : To make a mistake or do something really bad.',
  'See About : To seriously think about doing something.',
  'Sell Out : When all the inventory of a particular product has been purchased.',
  'Set Up : To organize or plan for an activity/event to happen.',
  'Settle Down : To begin living a stable and routine life.',
  'Settle For : To accept something even though it’s not what you want or need.',
  'Shake Up : To mix something in a container by shaking it.',
  'Show Off : To overly display your skills or what you have.',
  'Shut Off : To stop the operation of an electrical or mechanical device.',
  'Shut Up : To stop talking.',
  'Sign In : To write your name on a list to indicate the day and time you arrived at a certain place.',
  'Sign Out : To write your name on a list to indicate the day and time of your departure.',
  'Sit Down : To change from a standing to a sitting position.',
  'Slow Down : To do something slower.',
  'Sneak In/Into : To enter a place quietly to avoid being seen or heard.',
  'Sneak Out : To leave a place without being noticed.',
  'Sort Out : To arrange or separate things into groups according to similarities.',
  'Space Out : When someone’s attention is not in the present moment. [Adj.] {spaced out} To describe a person whose attention isn’t in the present moment.',
  'Stand Around : To stand in one place or area when you should be doing something.',
  'Stand For : To support or represent an idea, belief, etc.',
  'Stand Up : To rise from sitting or lying down to a vertical position.',
  'Start Off : The beginning of an event, activity or time period.',
  'Start Out : To begin a trip or venture to some place.',
  'Start Up : To start something.',
  'Stay Off : To avoid discussing a certain subject or topic.',
  'Stay Out : To spend time out of your own home.',
  'Stay Up : To remain in a place that is higher than ground level.',
  'Step On : To place your foot on something or someone.',
  'Stick Around : To stay in a place or with someone for any period of time.',
  'Stick Out : To extend something outward.',
  'Stick To : When something is attached to another by some form of adhesive.',
  'Stick Up : To use a weapon, especially a gun, to rob someone.',
  'Stick With : To continue to use or do something.',
  'Stop Off : To make a quick stop on your way to a destination.',
  'Stop Over : To visit someone for a short period of time.',
  'Straighten Out : To make something straight.',
  'Stress Out : To feel very worried, nervous or anxious.',
  'Switch Off : When you move something from the ‘on’ state to the ‘off’ state. Synonymous with “Turn Off.” Yesterday’s “Switch On” is the opposite.',
  'Switch On : When you move something from the ‘off’ state to the ‘on’ state. Synonymous with “Turn On,” while “Switch Off” is the opposite.',
  'Take Apart : To disconnect or separate the parts of an object.',
  'Take Back : To return something or someone.',
  'Take In : To be successfully tricked or deceived by someone.',
  'Take Out : To remove an object from an area, place or container.',
  'Take Out On : To direct your anger towards someone or something when you’re really upset about someone or something else.',
  'Take Up On : When you accept an invitation or offer from someone.',
  'Talk Down To : To talk to someone as if they are less intelligent than you by conveying a tone of voice or attitude that says so.',
  'Talk Into : To convince someone to do something.',
  'Talk Out Of : To convince someone not to do something.',
  'Talk To : To have a conversation with someone.',
  'Tear Down : To deconstruct a building or home.',
  'Tear Off : To remove with force.',
  'Tell Apart : To be able to differentiate something or someone from something or someone else.',
  'Tell On : To inform an authoritative figure about what someone else did.',
  'Think About : To consider something prior to making a final decision.',
  'Think Ahead : To think and plan carefully for a future situation or event.',
  'Think Up : To use your imagination to create a plan, idea, or a solution.',
  'Throw Away : To dispose of something you no longer find useful in a waste bin, trash, etc.',
  'Throw Out : When you get rid of something by putting it in a trash can, bin, etc.',
  'Throw Up : To vomit or puke.',
  'Track Down : To locate someone or something after a long search.',
  'Trade In : To exchange something old for something new.',
  'Trick Into : To convince or persuade someone to believe something untrue or to do something for you.',
  'Try On : To see how something fits or looks before purchasing.',
  'Try Out : To show that you are qualified to do something.',
  'Turn Around : When someone or something moves until it faces the opposite direction.',
  'Turn Down : To decrease the temperature, sound, etc.',
  'Turn In : To give someone or something to the police or someone of authority.',
  'Turn Into : To transform.',
  'Turn Off : To stop a device from functioning.',
  'Turn On : To cause someone to feel interested and/or attracted.',
  'Turn Out : To attend an event, meeting, etc.',
  'Turn Over : To move an object so that the part that is on top becomes the bottom and vice versa.',
  'Turn Up : To increase the controls of an electronic or mechanical device.',
  'Use Up : To completely consume or use all of a supply.',
  'Wake Up : When you are finished sleeping.',
  'Wash Off : To remove dirt or unwanted markings with soap and water.',
  'Wash Up : To clean your face, hands, body, etc.',
  'Watch Out : To be aware of someone or something.',
  'Wear Down : To make the surface or top of something disappear due to friction.',
  'Wear Off : To decrease or disappear gradually.',
  'Wear Out : When something is damaged or weakened from use and age.',
  'Wind Up : To operate a mechanical device by turning its handle.',
  'Wipe Off : To completely remove or clean something from a surface or location.',
  'Wipe Out : To clean the inside of something.',
  'Wipe Up : To remove liquid from a surface using a sponge, towel or cloth, etc.',
  'Work In : To make time in a busy schedule for a person or an activity.',
  'Work Out : When a situation, event, plan, or idea is successful.',
  'Work Up : To gradually improve at or make progress in something.',
  'Wrap Up : To cover something with some kind of special paper.',
  'Zip Up : To close an item that has a zipper.',
];



List<String> a1vocabulary =[
  'accountant     : muhasebeci',
  'afraid         : korkmuş',
  'age            : yaş, çağ',
  'alone          : yalnız',
  'airplane       : uçak',
  'angry          : kızgın',
  'animal         : hayvan',
  'answer         : cevap',
  'architect      : mimar',
  'arrive         : varmak',
  'aunt           : teyze, hala',
  'bag            : çanta',
  'ball           : top',
  'bath           : banyo',
  'beautiful      : güzel',
  'bill           : fatura',
  'body           : vücut',
  'boil           : kaynatmak, haşlamak',
  'bookstore      : kitapçı',
  'boring         : sıkıcı',
  'borrow         : ödünç alamk',
  'boss           : patron',
  'bottle         : şişe',
  'box            : kutu',
  'brave          : cesur',
  'bread          : ekmek, pane etmek',
  'break          : kırmak',
  'bridge         : köprü',
  'brush          : fırça, fırçalamak',
  'build          : inşa etmek',
  'butter         : tereyağı',
  'calculator     : hesap',
  'calendar       : takvim',
  'call           : arama',
  'capital        : sermaye, başkent',
  'carpenter      : marangoz',
  'carpet         : halı',
  'carry          : taşımak',
  'cheap          : ucuz',
  'cheese         : peynir',
  'cherry         : kiraz',
  'chicken        : tavuk',
  'church         : kilise',
  'clean          : temizlemek, temiz',
  'clear          : açık, net',
  'clever         : zeki',
  'clock          : saat',
  'cloud          : bulut',
  'coat           : ceket',
  'cold           : soğuk',
  'company        : şirket',
  'continue       : devam etmek',
  'correct        : doğru, düzeltmek',
  'country        : ülke',
  'cow            : inek',
  'cry            : ağlamak',
  'daily          : günlük',
  'dark           : karanlık',
  'dentist        : dişçi',
  'difficult      : zor',
  'dirty          : kirli',
  'divorced       : boşanmış',
  'draw           : çizmek',
  'early          : erken',
  'earn           : kazanmak',
  'elephant       : fil',
  'emergency      : acil durum',
  'empty          : boş',
  'engaged        : nişanlı',
  'engineer       : mühendis',
  'enough         : yeterli',
  'eraser         : silgi',
  'error          : hata',
  'fall           : düşmek',
  'far            : uzak',
  'farm           : çiftlik',
  'fat            : şişman',
  'finger         : parmak',
  'fire           : ateş',
  'flight         : uçuş',
  'floor          : zemin',
  'fork           : çatal',
  'friendly       : samimi',
  'fruit          : meyve',
  'funny          : komik',
  'garden         : bahçe',
  'glass          : bardak',
  'grape          : üzüm',
  'gun            : tabanca',
  'habit          : alışkanlık',
  'half           : yarım',
  'hand           : el',
  'handsome       : yakışıklı',
  'hate           : nefret',
  'health         : sağlık',
  'hear           : duymak',
  'heart          : kalp',
  'heavy          : ağır',
  'high           : yüksek',
  'history        : tarih',
  'horror         : korku',
  'hungry         : aç',
  'ill            : hasta',
  'interested     : ilgili',
  'job            : meslek',
  'journalist     : gazeteci',
  'kill           : öldürmek',
  'large          : büyük',
  'laugh          : gülmek',
  'lawyer         : avukat',
  'leave          : ayrılmak',
  'left           : sol',
  'lend           : ödünç vermek',
  'letter         : mektup',
  'library        : kütüphane',
  'lunch          : öğle yemeği',
  'manager        : müdür',
  'main           : ana',
  'map            : harita',
  'married        : evli',
  'meal           : yemek',
  'meet           : karşılamak, buluşmak, karşılaşma',
  'meeting        : toplantı, buluşma, görüşme',
  'melon          : kavun',
  'minute         : dakika',
  'mirror         : ayna',
  'miss           : kaçırmak,ıska geçmek',
  'mistake        : hata',
  'month          : ay',
  'need           : gerek',
  'neighbour      : komşu',
  'news           : haber',
  'nice           : güzel',
  'nose           : burun',
  'nurse          : hemşire',
  'object         : nesne',
  'opposite       : karşısında, ters, zıt, karşıt',
  'oven           : fırın',
  'page           : sayfa',
  'paint          : boya, boyamak',
  'parent         : ebeveyn',
  'pass           : geçmek, geçirmek',
  'pay            : ödeme, ödemek',
  'pepper         : biber',
  'personal       : kişisel',
  'pet            : evcil hayvan',
  'place          : yer',
  'plane          : uçak',
  'pocket         : cep',
  'polite         : kibar',
  'pool           : havuz',
  'poor           : yoksul',
  'possible       : mümkün',
  'push           : itmek',
  'quick          : hızlı',
  'quiet          : sessiz',
  'railway        : demiryolu',
  'ready          : hazır',
  'refrigerator   : buzdolabı',
  'remember       : hatırlamak',
  'rent           : kiralamak',
  'repair         : onarım, onarmak, tamir etmek',
  'repeat         : tekrar',
  'restroom       : tuvalet',
  'return         : dönüş',
  'rice           : pirinç',
  'rich           : zengin',
  'ride           : binmek',
  'right          : sağ',
  'ring           : halka',
  'rise           : artış',
  'river          : nehir',
  'road           : yol',
  'roof           : çatı',
  'room           : oda',
  'rose           : gül',
  'salt           : tuz',
  'same           : aynı',
  'security       : güvenlik',
  'sell           : satmak',
  'serious        : ciddi',
  'shelf          : raf',
  'ship           : gemi',
  'shirt          : gömlek',
  'shoe           : ayakkabı',
  'show           : göstermek',
  'sick           : hasta',
  'sing           : şarkı söylemek',
  'single         : tek',
  'skirt          : etek',
  'sky            : gökyüzü',
  'smile          : gülümsemek, gülümseme',
  'snow           : kar',
  'socks          : çorap',
  'son            : oğul, erkek evlat',
  'song           : şarkı',
  'soup           : çorba',
  'spend          : harcamak',
  'spoon          : kaşık',
  'stamp          : kaşe, pul, damgalamak',
  'stay           : Kalmak',
  'story          : öykü',
  'strawberry     : çilek',
  'strong         : güçlü',
  'successful     : başarılı',
  'suit           : takım elbise',
  'sweet          : tatlı',
  'talk           : konuşma',
  'tall           : uzun boylu',
  'teach          : öğretmek',
  'thick          : kalın',
  'thief          : hırsız',
  'thin           : ince',
  'think          : sanmak, düşünmek',
  'thirsty        : susuz, susamış',
  'ticket         : bilet',
  'tidy           : düzenli',
  'tired          : yorgun',
  'toothbrush     : diş fırçası',
  'toothpaste     : diş macunu',
  'towel          : havlu',
  'tower          : kule',
  'town           : kasaba',
  'toy            : oyuncak',
  'trainers       : spor ayakkabı',
  'travel         : seyahat',
  'tree           : ağaç',
  'trousers       : pantolon',
  'turn           : dönmek, dönüş',
  'ugly           : çirkin',
  'umbrella       : şemsiye',
  'uncle          : amca, dayı',
  'understand     : anlamak, kavramak',
  'underwear      : iç çamaşırı',
  'waiter         : garson',
  'waitress       : kadın garson',
  'wall           : duvar',
  'watermelon     : karpuz',
  'way            : yol',
  'weak           : zayıf',
  'wear           : giymek',
  'week           : hafta',
  'wind           : rüzgar',
  'wonderful      : harika',
  'winter         : kış',
  'word           : kelime',
  'wrong          : yanlış, hatalı',
  'zoo            : hayvanat bahçesi',

];

List<String> a2vocabulary =[
  'abroad     : yurtdışı',
  'accept     : kabul etmek',
  'accident   : kaza',
  'adventure  : macera',
  'agree      : anlaşmak, fikir birliği, uzlaşma',
  'anniversary: yıldönümü',
  'ant        : karınca',
  'area       : alan, bölge',
  'argue      : tartışma',
  'arm        : kol',
  'backgammon : tavla',
  'begin      : başlamak',
  'believe    : inanmak',
  'bell       : zil',
  'bite       : ısırmak',
  'blanket    : battaniye',
  'brain      : beyin',
  'bring      : getirmek',
  'business   : iş',
  'busy       : meşgul',
  'cable      : kablo',
  'can        : konserve kutusu, – e bilmek',
  'cap        : şapka',
  'cash       : nakit para',
  'catch      : yakalamak',
  'changing room: soyunma odası',
  'chess      : satranç',
  'chewing gum: sakız(çiğneme)',
  'chin       : çene',
  'choose     : seçmek',
  'climb      : tırmanmak',
  'cloth      : kıyafet, bez',
  'collect    : toplamak, biriktirmek',
  'complete   : tamamlama(başarılı bir şekilde)',
  'confused   : kafası karışık',
  'connect    : bağlanmak (veri)',
  'contact    : temasa geçmek, temas kurmak',
  'cookies    : kurabiyeler, çerezler',
  'cool       : rahat, serin, havalı',
  'cost       : mal oldu(fiyatı)',
  'cotton     : pamuk, pamuklu',
  'couch      : kanepe',
  'cough      : öksürük',
  'crazy      : çılgın',
  'curious    : meraklı',
  'customer   : müşteri',
  'cut        : kesmek',
  'cute       : sevimli',
  'damage     : hasar vermek',
  'dangerous  : tehlikeli',
  'dead       : ölü',
  'decide     : karar vermek',
  'deep       : derin',
  'delete     : silmek',
  'delicious  : lezzetli',
  'describe   : tanımlamak',
  'diamond    : elmas',
  'die        : ölmek',
  'direction  : yön',
  'discover   : keşfetmek',
  'discuss    : tartışmak',
  'disturb    : rahatsız etmek',
  'drawer     : çekmece',
  'dream      : rüya',
  'earring    : küpe',
  'elbow      : dirsek',
  'elevator   : asansör',
  'enjoy      : zevk almak, tadını çıkarmak',
  'entertainment: eğlence (sektörü)',
  'equal      : eşit',
  'escape     : çıkış yapmak',
  'excellent  : mükemmel',
  'expensive  : pahalı',
  'experience : deneyim toplamak, tecrübe etmek',
  'explain    : açıklamak',
  'eyebrow    : kaş',
  'eyelash    : kirpik',
  'eyelid     : göz kapağı',
  'face       : yüz',
  'factory    : fabrika',
  'fail       : başarısız',
  'famous     : ünlü',
  'fan        : fan, vantilatör, hayran, fanatik',
  'feel       : hissetmek',
  'female     : kadın, bayan',
  'fight      : dövüşmek, kavga',
  'fill       : doldurmak',
  'first aid  : ilk yardım',
  'flag       : bayrak',
  'flat       : düz, apartman dairesi',
  'flour      : un',
  'fog        : sis',
  'follow     : takip etmek',
  'food       : yiyecek',
  'foreign    : yabancı',
  'formal     : resmi',
  'fresh      : taze',
  'front      : ön',
  'fuel       : yakıt',
  'furniture  : mobilya',
  'future     : gelecek',
  'garlic     : sarımsak',
  'gate       : han kapısı, geçit',
  'generous   : cömert',
  'gift       : hediye',
  'glad       : memnun olmak',
  'glove      : eldiven',
  'graduate   : mezun olmak',
  'grass      : çimen, yeşillik',
  'grocer     : manav',
  'grow       : yetiştirmek, büyütmek',
  'guide      : rehber',
  'hard       : zor',
  'harmful    : zararlı',
  'huge       : yüce',
  'idea       : fikir',
  'impossible : imkansız',
  'insect     : böcek',
  'intelligent: zeki',
  'introduce  : tanıtmak',
  'invite     : davet etmek',
  'island     : ada',
  'jam        : reçel',
  'jar        : kavanoz',
  'join       : katılmak',
  'joke       : şaka yapmak',
  'journey    : seyahat',
  'juice      : meyve suyu',
  'jump       : atlamak',
  'key        : anahtar',
  'kick       : tekme atmak',
  'kind       : tür, kibar, nazik',
  'knee       : diz',
  'knife      : bıçak',
  'lake       : göl',
  'lamb       : koyun',
  'leather    : deri',
  'leg        : bacak',
  'lift       : kaldırmak',
  'lip        : dudak',
  'lock       : kilit, kilitlemek',
  'lose       : kaybetmek',
  'loud       : gürültü, yüksek sesli',
  'lovely     : sevimli',
  'luck       : şans',
  'magic      : sihir',
  'mall       : alışveriş merkezi',
  'meat       : et',
  'medicine   : ilaç, tıp, medikal',
  'mend       : tamir etmek',
  'mixed      : karıştırılmış, karışık',
  'monkey     : maymun',
  'moon       : ay',
  'mountain   : dağ',
  'mouth      : ağız',
  'move       : taşınmak, hareket etmek',
  'nail clippers: tırnak makası',
  'naughty    : afacan, yaramaz',
  'nervous    : asabi, sinirli, gergin',
  'noise      : gürültü',
  'novel      : roman',
  'ocean      : okyanus',
  'officer    : memur',
  'oil        : yağ, mazot',
  'overweight : aşırı yüklenmek, kilo fazlası',
  'pick       : seçmek',
  'plant      : ekmek, dikmek, bitki',
  'plate      : levha, plaka',
  'poem       : şiir',
  'point      : uç, nokta, puan',
  'point on   : (parmakla) işaret etmek',
  'power      : güç, enerji',
  'prepare    : hazırlamak',
  'pretty     : şirin,tatlı',
  'price      : bedel, fiyat',
  'produce    : üretmek, imal etmek',
  'queen      : kraliçe',
  'reach      : ermek, erişmek, uzanmak',
  'reason     : sebep, gerekçe',
  'record     : kaydetmek',
  'refuse     : reddetmek, geri çevirmek',
  'relation   : ilişki, bağlantı',
  'relax      : rahatlamak, dinlenmek',
  'remote control: uzaktan kumanda',
  'reply      : yanıtlamak, cevap',
  'report     : şikayet etmek, rapor vermek',
  'retire     : emekli olmak',
  'rock       : yıkmak, kaya',
  'rope       : halat, ip',
  'rude       : kaba saba, kaba',
  'rule       : kural, yönetmek, hükmetmek',
  'safe       : kasa, güvenilir, tehlikesiz',
  'salary     : maaş, aylık',
  'save       : tasarruf etmek, kurtarmak',
  'scissors   : makas',
  'seat       : koltuk (yerinden hareket ettirilemeyen)',
  'select     : seçmek',
  'send       : göndermek',
  'situation  : durum, hal',
  'serious    : ciddi',
  'serve      : hizmet etmek',
  'sharp      : keskin, sivri',
  'shine      : parlatmak',
  'shoulder   : omuz',
  'shout      : haykırmak',
  'sign       : imzalamak',
  'silent     : sessiz',
  'simple     : sade, basit',
  'ski        : kayak',
  'snake      : yılan',
  'soap       : sabun',
  'society    : toplum',
  'soft       : yumuşak',
  'spider     : örümcek',
  'stand      : stand, ayakta durmak',
  'stone      : taş',
  'storm      : fırtına',
  'subway     : alt geçit',
  'sure       : emin, kesin, elbette',
  'surprised  : hayret etmiş',
  'tailor     : terzi',
  'taste      : tatmak, tadı olmak',
  'team       : ekip',
  'temperature: sıcaklık',
  'tent       : çadır',
  'terrible   : korkunç',
  'throw      : fırlatmak',
  'tiger      : kaplan',
  'tissue     : mendil',
  'tongue     : dil, uzantı, lisan',
  'touch      : dokunmak',
  'transport  : nakletmek, taşımak',
  'trouble    : problem',
  'try        : denemek',
  'usual      : sıradan',
  'vacation   : tatil',
  'vacuum cleaner: elektrik süpürgesi',
  'valuable   : kıymetli',
  'vegetable  : sebze',
  'view       : görmek, seyretmek, görüş',
  'voice      : ses',
  'war        : savaş',
  'warm       : ılık, sıcak',
  'warning    : uyarı',
  'weather    : hava durumu',
  'wet        : ıslatmak',
  'win        : kazanmak',
  'wine       : şarap, şarap içmek',
  'chance     : şans',
  'worry      : endişelenmek',


];